### ISSUE TITLE
Convert Tableau Dashboard to Tableau Public for embedding

### ISSUE THREAD

**Issue by rsm-aburda** [rsm-aburda/MGTA-452-Final-Project#4]
Please convert the Tableau dashboard to a Tableau Public dashboard so that we can embed a live dashboard on the website.

**Comment by rsm-jal167** [comment]
I think I can push the dashboard into public. That was we can present dynamic dashboard.

**Comment by rsm-aburda** [comment]
Ok amazing let's sync up tomorrow and take a look. Could you either email more or paste here the public link?

**Comment by rsm-jal167** [comment]
https://public.tableau.com/app/profile/hakjin.lee/viz/Book1_17331226976950/TopsongsbyArtist?publish=yes

**Comment by rsm-jal167** [comment]
problem is that I can only publish one page

**Comment by rsm-jal167** [comment]
`<div class='tableauPlaceholder' id='viz1733381475207' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Sp&#47;SpotifyViz_17333811658780&#47;TopSongsbyArtists&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='SpotifyViz_17333811658780&#47;TopSongsbyArtists' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Sp&#47;SpotifyViz_17333811658780&#47;TopSongsbyArtists&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1733381475207');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1400px';vizElement.style.height='950px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1400px';vizElement.style.height='950px';} else { vizElement.style.width='100%';vizElement.style.height='1250px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>`

**Comment by rsm-jal167** [comment]
https://public.tableau.com/views/SpotifyViz_17333811658780/TopSongsbyArtists?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link

**Comment by rsm-jal167** [comment]
@rsm-aburda - Spotify Viz is published on the Tableau public
