### ISSUE TITLE
Live Spotify Data?

### ISSUE THREAD

**Issue by rsm-aburda** [rsm-aburda/MGTA-452-Final-Project#5]
Either a separate page (with visuals like a dashboard) or a embedded dashboard

**Comment by rsm-aburda** [comment]
I added this component to the home page where users can authenticate their Spotify account. I have to still add users emails to the beta test site. This is why this feature is not currently working for everyone.

**Comment by rsm-aburda** [comment]
Ok everyone here has been added as users. when you get a chance please confirm this part is working for you

**Comment by rsm-jal167** [comment]
I am not sure if it's just me but I cannot see anything.

**Comment by rsm-aburda** [comment]
Ope sorry about that I misspelled the email - please try again and let me know
